#include <stdio.h>

#define COMMAND(NAME, TYPE) TYPE##_##NAME##_command

#define DEFINE_COMMAND(NAME, TYPE) \
    void COMMAND(NAME, TYPE)(void) {}

#define DEFINE_EXTERNAL_COMMAND(NAME) \
    DEFINE_COMMAND(NAME, EXTERNAL)

#define DEFINE_INTERNAL_COMMAND(NAME) \ 
DEFINE_COMMAND(NAME, INTERNAL)

#define CALL_COMMAND(NAME, TYPE) COMMAND(NAME, TYPE)()

#define CALL_EXTERNAL_COMMAND(NAME) \
    CALL_COMMAND(NAME, EXTERNAL)

#define CALL_INTERNAL_COMMAND(NAME) \ 
CALL_COMMAND(NAME, INTERNAL)

DEFINE_INTERNAL_COMMAND(quit)

int main()
{
    CALL_INTERNAL_COMMAND(quit);

    return 0;
}
